### ISSUE TITLE
Sidebar expanded by default

### ISSUE THREAD

**Issue by mkramb** [jenkinsci/jenkins-design-language#197]
The sidebars define if it's in a collapsed mode based on the value stored in local storage:
https://github.com/jenkinsci/jenkins-design-language/blob/master/components/Sidebar/SidebarBehavior.ts#L42

Which means that it's always initially expanded. I think it should be collapsed by default or even better approach would be to pass a prop with an initial value so that the application controls that.

**Comment by lausena** [comment]
I've added a default property with an initial value of "expanded". 

<img width="869" alt="jenkins-design-language____developer_cloudbees_repos_jenkins-design-language__-_____components_sidebar_sidebar_stories_tsx__jenkins-design-language_" src="https://user-images.githubusercontent.com/7661849/43080120-f7d9a3d8-8e5c-11e8-9795-78e6e156874e.png">

[PR-200](https://github.com/jenkinsci/jenkins-design-language/pull/200)
