### ISSUE TITLE
JDL2 tooling setup

### ISSUE THREAD

**Issue by mkramb** [jenkinsci/jenkins-design-language#199]
Each component (package) should define own dependencies versions for `React`, `ReactDom` - we need to control that per package, e.g. if something requires minimum React 16+. Also, a suggestion, common tooling (e.g.  `jdl-component-creator.js`, `storybook`, `styleguide`, ... ) can be available as a shared package (e.g. `/utils/shared`), again so that we can introduce breaking changes without affecting every component.

**Comment by kzantow** [comment]
It would be nice to specify compatible versions but components can be designed for react 15 & 16 (and presumably higher) and work fine so the version would have to be: `^15` which is *almost* effectively `*`. What I don't want to do is: a) have something that results in multiple copies of React in the user's bundles or b) prevent users from upgrading React needlessly. By specifying a wildcard version, at least it lets the consumer try to use these without having to continually upgrade.

As for the other comment about storybook, style guide and such, these are not intended to be consumed downstream.
